name: delete
# an example workflow that also monitors success of the preview api

on:
  schedule:
    - cron: '5 */0 * * *'
    # every 6 hours

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: windows-latest

    steps:
    - run: echo hello > world.txt

    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: world.txt

    - uses: geekyeggo/delete-artifact@v1
      with:
        name: my-artifact
